travis:
  secure:
    BINSTAR_TOKEN: B/2R5zy5apR+bgz6O2zvr9avzpGzIb6DuQyj+PwYZvxRQMVM2JCMf/FkFkBCquZkAnUhjJjzO3R3Gs9GrTsfmAMrVriWR70xVIqGYs7SINdRRUhC2x4Rh4QlEoDMyTp6GQXXEs/h/JF9zsJG+RUGaLB3oGv9SC3z9nAoMjrb37mAsdy1JzpAUvyqvll/eGeEYWypCCHyIlRdTpnxSMSkd0EduH0BGZXy5XWlI8R8CvTRAi1GkkTdXKGYrEGbAcaN4ogwxdfQt8FVtOjVCrNWNDQQ4zb8kV0tY7bnBCN6iQ0k34puScmI8HJFXJ/vkVNnZyxH1W3awxBh0fQTrPY/YT6o7QGkNAq1v2SgFt9fpHwxikP7sx23SfcEHR9q8nBZggu9SS8M0R4QjUAjKcUDj5PJTGlbQE+jp2Rr/NujIvdcDHyPUH8jDngvR/vScC1BDs/w29LyC/IUqTr8H2EqmNhEoQJzMYvFIzmHT+BQECoX01iLiiusmC+MbOEChHbhIamTnhN7m20cwGPkVuIUhlxkoszZGeVBbrUTKyq0jVldKpGISLz4uEVeHChs6yJS5Wh5e64mcz/LgoGv5f8Q4DkyN8ThTBvXhnQ6tyKvQg4HmGAMEsHWs3KnGnEqsf1U82psEDT8KG9hQK1g1PsrtVO4yN71orKGP7P8U+p7R8s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
